---
- name: Configure UFW rules
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"

- name: Enable UFW
  ufw:
    #state: enabled
    state: reloaded
  #async: 60
  #poll: 0